[profilecli/canary-exporter] Fix probe_success metric description
grafana/pyroscope pull request #2810
Opened 2023-12-06 13:37 UTC by vaxvms

2023-12-06 13:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/grafana/pyroscope?pullRequest=2810) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/grafana/pyroscope?pullRequest=2810) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/grafana/pyroscope?pullRequest=2810) it.</sub>

2023-12-07 06:00 UTC, kolesnikovae requested changes
Thank you for the contribution @vaxvms! I suggest to slightly alter the proposed description so it reflects the nature of the measurement

2023-12-07 08:24 UTC, vaxvms commented on cmd/profilecli/canary_exporter.go
> +			Help: "Total number of successful probe",
Doh, i blindly though it was a counter. Thank for pointing it out. I'm fixing

2023-12-08 05:23 UTC, kolesnikovae approved these changes
Thank you @vaxvms once again!

2023-12-08 06:44 UTC, merged