POC feat(symbolization): Add DWARF symbolization with debuginfod support
grafana/pyroscope pull request #3799
Opened 2024-12-20 11:10 UTC by marcsanmi

### Context
This PR introduces a **POC** implementation for DWARF debug information symbolization. The implementation can fetch debug info from debuginfod servers or local files and resolve memory addresses to source code locations.

### Key features
- Remote debug info fetching via debuginfod
- Local debug info file support
- DWARF debug info parsing and address resolution
- Support for inline function resolution
- Memory address normalization for different ELF types

**Note:** While this POC demonstrates the core symbolization functionality, a production-ready implementation would require several additional components: a robust debuginfod client with retries and rate limiting, proper caching mechanisms for both debug files and symbolization results, fallback symbolization methods (e.g., symtab) when DWARF isn't available, comprehensive error handling, and security considerations around file handling and network requests.

To run it:
1. Run the main program with default debuginfod server and  `buildID`
2. Optionally modify the client to use a local debug info file
3. Optionally enable `SymbolizeAll` to explore all available symbols

Example usage in `main.go` shows both specific address symbolization and full binary exploration (commented out by default as they are alternative approaches).

2025-01-15 19:40 UTC, petethepig commented on pkg/experiment/symbolization/debuginfod_client.go
> +	filePath := filepath.Join(tempDir, fmt.Sprintf("%s.elf", buildID))
I'd also add that generally speaking we should also be avoiding file operations as much as possible. If it's possible to do this in memory I'd do this in memory. If the file is too large to fit in memory I'd see if we could stream it

2025-01-17 08:37 UTC, korniltsev commented on pkg/phlaredb/symdb/resolver.go
> +	if len(loc.Line) == 0 {
I guess it's time to move this logic (unsymbolized fallback) https://github.com/grafana/pyroscope/blob/466aaa8194e06aab452b00f56efd5ddd8bcff311/pkg/ingester/otlp/convert.go#L166 somewhere here to Symbols/resolver

2025-01-17 09:05 UTC, kolesnikovae reviewed
Good work, Marc! I'm excited to see some experimental results 🚀

I think we can implement a slightly more optimized version for production use:

```mermaid
sequenceDiagram
    autonumber

    participant QF as Query Frontend
    participant M  as Metastore
    participant QB as Query Backend
    participant SYM as Symbolizer

    QF ->>+M: Query Metadata
    Note left of M: Build identifiers are returned<br> along with the metadata records
    M ->>-QF: 

    par
        QF ->>+SYM: Request for symbolication
        Note left of SYM: Prepare symbols for<br>the objects requested
    and
        QF ->>+QB: Data retrieval and aggregation
        Note left of QB: The main data path<br>Might be serverless
    end

    QB ->>-QF: Data in pprof format
    Note over QF: Because of the truncation,<br> only a limited set of locations<br>make it here (16K by default) 

    QF --)SYM: Location addresses
    
    SYM ->>-QF: Symbols
    
    QF ->>QF: Flame graph rendering
```

Even without a parallel pipeline and dedicated symbolication service, we could implement something like this:

```mermaid
sequenceDiagram
    autonumber

    participant QF as Query Frontend
    participant M  as Metastore
    participant QB as Query Backend
    participant SYM as Symbols

    QF ->>+M: Query Metadata
    Note left of M: No build identifiers are returned
    M ->>-QF: 

    QF ->>+QB: Data retrieval and aggregation
    Note left of QB: The main data path<br>Might be serverless

    QB ->>-QF: Data in pprof format
    Note over QF: Because of the truncation,<br> only a limited set of locations<br>make it here (16K by default)

    QF ->>+SYM: Fetch symbols
    SYM ->>-QF: Symbols
    Note over QF: In terms of the added latency,<br>this approach is not worse than<br>block level symbolication
    
    QF ->>QF: Flame graph rendering
```

I think we should avoid symbolization at the block level if the symbols are not already present in the block itself. Otherwise, this approach leads to excessive processing, increased latency, and higher resource usage. Please keep in mind, that a query may span many thousands of blocks.

I won't delve too deeply into how we fetch and process ELF/DWARF files, but I strongly doubt we can bypass the need for an intermediate representation optimized for our access patterns. Additionally, we need a solution to prevent concurrent access to the debuginfod service.

2025-01-17 10:49 UTC, korniltsev commented
I have not look into the code yet, but I've tried to run it locally and it looks like it's trying to load a lot of unnecesarry debug files.

I run ebpf profiler with no ontarget symbolization , also run a simple `python -m http.server` to mock debug infod responses.

I then query  only one executable `process_cpu:cpu:nanoseconds:cpu:nanoseconds{service_name="unknown", process_executable_path="/home/korniltsev/.cache/JetBrains/IntelliJIdea2024.2/tmp/GoLand/___go_build_go_opentelemetry_io_ebpf_profiler"}` 

I see 268 GET  requests, with 13 requests to `"GET /buildid/fbce2598b34f1cf8d0c899f34c2218864e1da6d1/debuginfo HTTP/1.1" 200 -` (which is the profiler binary I put into mock server for testing and a bunch of 404 which I assume are build ids for the filles in the other processes which the query does not target. 

Other then that it works \M/  Can't wait to run it in dev.

![image](https://github.com/user-attachments/assets/b91bf779-4b16-463e-84a8-40ad2be4082b)

2025-02-12 11:11 UTC, marcsanmi commented on pkg/phlaredb/symdb/resolver.go
> +	if len(loc.Line) == 0 {
This was changed in https://github.com/grafana/pyroscope/pull/3792.

2025-02-14 15:09 UTC, marcsanmi commented on pkg/experiment/query_backend/backend.go
> +
I believe this no longer applies since I'll be moving it into the Query Frontend.

2025-02-18 11:39 UTC, liaol commented
Hi @marcsanmi , when can this PR be merged? 
Thanks

2025-02-19 17:32 UTC, marcsanmi commented
Hi @liaol,
It's still going to take a little while :)

2025-03-03 16:17 UTC, marcsanmi commented
I've created this diagram to outline the current Pyroscope Symbolization:
```mermaid
flowchart TD
    A[SymbolizePprof] --> B{Group by Mapping}
    B --> C[Symbolize Request]
    
    subgraph "Symbol Cache Layer (LRU)"
        D{Check Symbol Cache}
        D -->|Cache Hit| E[Return Cached Symbols]
        D -->|Cache Miss| F{Check ObjstoreCache}
    end
    
    C --> D
    
    subgraph "Persistent Cache Layer"
        F -->|Cache Hit| G[Read from ObjstoreCache]
        F -->|Cache Miss| H[Fetch from Debuginfod]
    end
    
    subgraph "Debuginfod Client Layer (Ristretto)"
        H --> I{Check Debuginfod Cache}
        I -->|Cache Hit| J[Return Cached Debug File]
        I -->|Cache Miss| K[HTTP Request to Debuginfod]
        K --> L[Store in Debuginfod Cache]
    end
    
    L --> M[Parse ELF/DWARF]
    G --> M
    
    subgraph "DWARF Resolution Layer"
        M --> N[Resolve Addresses]
        N --> O{Check Address Map}
        O -->|Map Hit| P[Return from Map]
        O -->|Map Miss| Q[Parse DWARF Data]
        Q --> R[Build Lookup Tables]
        R --> S[Store in Address Map]
        S --> T[Return Symbols]
        P --> T
    end
    
    T --> U[Update Symbol Cache]
    U --> V[Return to Caller]
    E --> V
```

2025-03-04 02:10 UTC, kolesnikovae commented on pkg/test/integration/testdata/otel-ebpf-profiler-offcpu-cpu.json
You can rename fixtures to `.json.bin` to make GitHub and IDEs to treat the files as binary

2025-03-04 06:21 UTC, kolesnikovae commented
I might be missing some details, but I have doubts about the cache hierarchy.

Now it looks like we have: symbols_cache -> object_store -> in_memory_object_store (ristretto) -> debuginfod.

As far as I understand, we're going to read from object_store even if there just a single unresolved address.

I expected to see: symbols_cache -> in_memory_object_store (ristretto) -> object_store -> debuginfod.

Could you please elaborate about the decision?

2025-03-04 08:53 UTC, alsoba13 commented on cmd/pyroscope/help-all.txt.tmpl
I wonder if we should discard this while symbolizer remains "experimental"

2025-03-04 15:57 UTC, marcsanmi commented on pkg/experiment/symbolizer/cache.go
> +
Yes, this should be handled by a separate job that runs periodically, removing unused objects. Instead of relying on last modification, we should track and remove based on last access patterns (afaik, there's no built-in attribute like that); I'll remove this for now and add a TODO.

2025-03-04 18:54 UTC, marcsanmi commented
> I might be missing some details, but I have doubts about the cache hierarchy.

You're right @kolesnikovae. I've just realized the problem is that the ristretto cache is coupled inside the debuginfod client. I'll decoupled it and placed it at symbolizer level. Thus, we'll be able to have the following path:

symbols_cache -> in_memory_object_store (ristretto) -> object_store -> debuginfod

2025-03-05 11:16 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	return NewProfileSymbolizer(client, cache, metrics, symbolCacheSize), nil
I made objstore cache is optional because the symbolizer might just work with just in-memory caching. Making it opt-in gives us flexibility - simple setups can avoid the operational overhead while larger ones can enable it when needed.. LMKWYT

2025-03-05 15:41 UTC, marcsanmi commented on cmd/pyroscope/help-all.txt.tmpl
Yep good point, thanks! I've just placed them under v2 umbrella in here fd39d9e6fe82cda59c39ffa76aeccda10737c6fa

2025-03-17 09:20 UTC, kolesnikovae commented on pkg/experiment/ingester/segment.go
> +	ds.needsSymbolization = !hasSymbols(p)
I think it should be:
```go
if !ds.needsSymbolization {
  // ...
}
```
Otherwise, if the last profile does not need symbols we reset the flag that could be set previously.

As optimization, we probably should detect it just once in the very end at flush time (instead of calling `hasSymbols` for each profile)

2025-03-20 06:55 UTC, liaol commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +						r.Tree = &queryv1.TreeReport{Tree: treeBytes}
here must add  `r.ReportType = queryv1.ReportType_REPORT_TREE` , because `querySingle()` in `pkg/frontend/read_path/query_frontend/compat.go`  will check ` x.ReportType == t`

2025-03-21 05:18 UTC, kolesnikovae commented on pkg/experiment/ingester/segment.go
> +	ds.Labels = allLabels
Well, `Build` should be called once, after all the labels where added. If it does not work, it's a bug in the label builder that should be fixed

2025-03-21 10:25 UTC, marcsanmi commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +						r.Tree = &queryv1.TreeReport{Tree: treeBytes}
Thanks for checking, I've added it in the latest commit 👍

2025-03-21 10:44 UTC, liaol commented on pkg/experiment/symbolizer/symbolizer.go
> +							Name:      nameIdx,
missing `Id:        uint64(funcIdx)`

2025-03-21 10:48 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +							Name:      nameIdx,
I have this fixed locally. Today I'll push a new commit with it along with some other  small fixes/improvements. Thanks again for taking a look at this :)

2025-03-22 10:45 UTC, marcsanmi commented on pkg/experiment/ingester/segment.go
> +	ds.Labels = allLabels
It was a non-related issue to this. Changed it back :)

2025-03-22 13:24 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfod_client.go
> +	}
It makes sense; I've just made it mandatory

2025-03-22 13:25 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfod_client.go
> +	inFlightRequestsMutex sync.Mutex
Didn't know about it, great suggestion!

2025-03-22 13:26 UTC, marcsanmi commented on pkg/test/integration/testdata/otel-ebpf-profiler-offcpu.json.bin
I've tried with 
```
testdata/* binary
```
```
testdata/* -text
```
And running `git add --renormalize .`, but nothing changed... I'll further investigate.

2025-03-22 13:27 UTC, marcsanmi commented on pkg/experiment/symbolizer/cache.go
> +}
Updated it to `DebugInfoStore`

2025-03-24 02:00 UTC, liaol commented on pkg/experiment/symbolizer/reader.go
> +	// Read all data into memory since we need to return an io.ReaderAt
This may use lots of memory when there is a big bianry,  using os.File.ReadAt would be better.

2025-04-03 12:39 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +			mapping := profile.Mapping[loc.MappingId-1]
IMO this is incorrect. you can not use ID for index into Mapping/Function/Location tables

2025-04-03 12:56 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +			mapping := profile.Mapping[loc.MappingId-1]
If the pprof is generated by the backend, it should work. This optimization is assumed along the entire read path

2025-04-04 04:54 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +			mapping := profile.Mapping[loc.MappingId-1]
TIL

2025-04-17 12:07 UTC, korniltsev commented on pkg/test/integration/testdata/otel-ebpf-profiler-offcpu-cpu.json.bin
> -          "lines": [
I think we should keep these synthetic frames if we do not symbolize them or fail to symbolize

Consider this flamegraph
![Screenshot 2025-04-17 at 13 37 39](https://github.com/user-attachments/assets/7b877f33-1c8c-4e8d-b4a1-92044652d5fd)

It hides the whole userspace stack. it is at least make harder to debug things for us, and at most may change the shape and look of flamegraph drastically if these frames are skipped in the middle of symbolized frames

2025-04-17 12:10 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	symbolCache     *lru.Cache[string, []lidia.SourceInfoFrame]
can the cache key be a struct with multiple fields instead of string?

2025-04-17 12:17 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		FilePath:     fmt.Sprintf("mapped_0x%x", addr),
I think we can leave FilePath empty. I'ts not visible anywhere and not useful. Mapping file path is enough.

2025-04-22 09:20 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	"github.com/dgraph-io/ristretto"
I wanted to avoid generics 😁 I'm updating it

2025-04-22 10:27 UTC, marcsanmi commented on pkg/test/integration/testdata/otel-ebpf-profiler-offcpu-cpu.json.bin
> -          "lines": [
I think this is happening for somewhat strange behaviour. I'm getting the following mappings:
```
1: 0x0/0x0/0x0   
2: 0x28000/0x1b0000/0x28000 libc.so.6 42c84c92e6f98126b3e2230ebfdead22c235b667 
3: 0x0/0x2000/0x0 linux-vdso.1.so
```
Mapping 1 has ~880 locations, so it's likely the one with userspace data. However, without a valid build id, we skip it; it's not even reaching symbolization. It's strange as we had valid build ids for `pyroscope-ebpf/profiler` before 🤔 

This is for the `pyroscopee-ebpf-otel-dev-001/otel-profiler`

<img width="1630" alt="Screenshot 2025-04-22 at 12 24 33" src="https://github.com/user-attachments/assets/a47416cd-446f-4618-b102-54ea7f926fb3" />

2025-04-25 14:50 UTC, korniltsev commented on pkg/phlare/phlare.go
> +	c.v2Experiment = os.Getenv("PYROSCOPE_V2_EXPERIMENT") != ""
don't we already have `c.v2Experiment = os.Getenv("PYROSCOPE_V2_EXPERIMENT") != ""`  in `registerServerFlagsWithChangedDefaultValues` , do we need this duplication?

2025-04-25 15:08 UTC, korniltsev commented on pkg/experiment/ingester/segment.go
> +		lb.WithLabelSet(model.LabelNameServiceName, f.head.key.service, metadata.LabelNameHasNativeProfiles, "true")
why do we set service name here second time?

2025-04-25 15:09 UTC, korniltsev commented on pkg/experiment/ingester/segment.go
> +
are these functions used or needed? getFunctionById isHexAddress

2025-04-26 09:49 UTC, kolesnikovae requested changes
Please cleanup the code after LLM

2025-04-26 09:49 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +		}
* We don't want update to metrics on each resolved location: it's expensive and not useful: me are measuring memory latency here.
* We don't want to write a log message on each failed `Lookup`. it will kill the system.

2025-04-26 09:49 UTC, kolesnikovae commented on pkg/experiment/symbolizer/addrmapper.go
> +func MapRuntimeAddress(runtimeAddr uint64, ei *BinaryLayout, m Mapping) (uint64, error) {
@korniltsev could you please take a careful look? I assume we should have something very similar in the profiler-side symbolizer.

2025-04-26 09:49 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +		}
I'd try to normalize all addresses before trying to resolve them.

2025-04-26 09:49 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +	s.updateProfileWithSymbols(profile, mapping, locs, req.Locations)
The code generated by LLM is extremely inefficient and might be invalid. Please consider an alternative:
1. We split profile by mappings. Each such profile only contains Locations, Mappings (just one), and StringTable.
2. Each such sub-profile is symbolized independently in-parallel (bound)
3. Symbolized profiles are merged.

2025-04-26 09:49 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +}
A comment explaining the sequence and cache layers would be helpful.

2025-04-26 13:48 UTC, kolesnikovae requested changes

2025-04-26 13:48 UTC, kolesnikovae commented on pkg/experiment/symbolizer/metrics.go
> +	}
Do we use it?

2025-04-26 13:48 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +	f.BoolVar(&cfg.Enabled, "symbolizer.enabled", true, "Enable symbolization for unsymbolized profiles")
Should probably be disabled by default

2025-04-26 13:48 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +			s.metrics.cacheOperations.WithLabelValues("objstore_cache", "put", StatusErrorUpload).Observe(time.Since(cacheStart).Seconds())
We already measure it inside the bucket implementation.

2025-04-26 15:27 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	f.BoolVar(&cfg.Enabled, "symbolizer.enabled", true, "Enable symbolization for unsymbolized profiles")
I think we talked to enabled it by default, but I might be wrong 🤔

2025-04-26 15:46 UTC, marcsanmi commented on lidia/builder.go
> +	}
Not as of now.

2025-04-26 15:55 UTC, marcsanmi commented on lidia/constants.go
> +
It shouldn't invalidate existing Lidia files. The file format is self-describing through its header, which stores the actual field sizes used in that particular file. When reading a file, the code uses these stored values rather than relying on the constant in the source code.
Therefore, this change would be backward compatible with existing objects.

2025-04-26 15:56 UTC, marcsanmi commented on lidia/constants.go
> +
`lineTableFieldsSize` primarily affect sthe calculation of section offsets during file creation. When reading files, the code uses the field size information stored in the file's header; it shouldn't invalidate existing Lidia files.

2025-04-26 16:12 UTC, marcsanmi commented on lidia/constants.go
> +
I'll remove the constant to properly calculate this dynamically as:
```go
entrySize := 4
if hdr.lineTablesHeader.fieldSize == 4 {
    entrySize = 8
}
hdr.binaryLayoutHeader.offset = hdr.lineTablesHeader.offset + uint64(len(rc.lb.entries)*entrySize)
```
But answer your question, no, this should only affect the offset calculation when writing a new file, ensuring that the binary layout section starts at the correct position. It has no impact on how we read existing files.

2025-04-27 19:01 UTC, marcsanmi commented on pkg/experiment/ingester/segment.go
> +
not anymore, good catch 👍

2025-04-28 07:29 UTC, korniltsev commented on pkg/experiment/symbolizer/addrmapper.go
> +func MapRuntimeAddress(runtimeAddr uint64, ei *BinaryLayout, m Mapping) (uint64, error) {
1. REL is not something can be loaded , we should not handle these 
2. for EXEC base address is always 0
3. for DYN, the otle ebpf profiler always outputs addresses relative to the elf base, so if an elf has a function at 0xcafe and the library is loaded at 0x7f0000000000, the profiler outputs just 0xcafe. We may need this addrmapper if in the future some other profiler outputs non relative addresses - 0x7f000000cafe. I remember we found a bug somewhere here in addrmapper  when debug elf and source elf had different PT_LOAD addresses and this code was outputting incorrect addresses for a debug-only file. This was an alloy binary. And in the case of full binary it was correct and the base offset was calculated as zero because it was an otel profile. I think we either need to solve this issue and make it work for both debug-only elfs and regular elfs including debug sections and have tests for these cases. Or just remove this addrmapper alltogether and assume the base is always zero (until we find some other non otel profiler which outputs  outputs non relative addresses)

2025-04-28 07:33 UTC, kolesnikovae commented on pkg/experiment/symbolizer/addrmapper.go
> +func MapRuntimeAddress(runtimeAddr uint64, ei *BinaryLayout, m Mapping) (uint64, error) {
This is my understanding as well: we do not want to normalize addresses at lookup time. For DYN, it should be done either in profiler, or during the translation to lidia.

2025-04-28 10:03 UTC, marcsanmi commented on pkg/experiment/symbolizer/addrmapper.go
> +func MapRuntimeAddress(runtimeAddr uint64, ei *BinaryLayout, m Mapping) (uint64, error) {
> the otle ebpf profiler always outputs addresses relative to the elf base

I wasn't aware of it. Considering this, I'd say we can remove it. As Tolyan mentioned, this will also simplify implementation since lidia binary layout won't be needed anymore (at least for now).

2025-04-28 15:07 UTC, marcsanmi commented on lidia/constants.go
> +
N/A anymore since we removed `MapRuntimeAddress` so no binaryLayout is needed anymore.

2025-04-28 15:21 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfod_client.go
> +	}
> NumCounters – do we want to make it configurable?
Maybe isn't needed from the beginning. We can always expose it later.

2025-04-28 15:23 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfod_client.go
> +		},
yep, now we use `backoff.Config` from dskit.

2025-04-29 05:48 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	if s.symbolCache == nil {
when is s.symbolCache nil?

2025-04-29 05:51 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	if s.lidiaTableCache != nil {
when is it nil?

2025-04-29 06:03 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	// Create a reader from the data
Lets remove all the "obvious" comments all over the new package. They are not very useful.

> // Create a reader from data
> ... bytes.NewReader
> 
> // Create lidia file
> lidia.CreateLidiaFromElf
> 
> 		// Convert to our internal binary layout format
>		ei = convertBinaryLayout(lidiaLayout)
> 
> // Open the Lidia table to extract binary layout
> lidia.Open

2025-04-29 06:08 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	if s.store != nil {
when is s.store nil?

2025-05-06 09:32 UTC, marcsanmi commented on pkg/phlare/modules_experimental.go
> +	}
I thought as the following:

The symbolizer should have two levels of configuration: the global flag and per-tenant settings. The global flag (symbolizer.enabled) controls whether the symbolization is available at all. If enabled globally, then we can opt-in via the tenant configuration. If disabled globally, no symbolization will happen regardless of tenant settings.

2025-05-06 20:47 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +}
We simplifed a lot.

2025-05-06 20:54 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	DefaultInMemoryLidiaTableCacheSize = 2 << 30 // 2GB default
N/A

2025-05-07 02:39 UTC, korniltsev commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +}
no, we don't add this label to samples. only series.

2025-05-07 03:22 UTC, korniltsev commented on pkg/validation/limits.go
> +	SymbolizerEnabled bool `yaml:"symbolizer_enabled" json:"symbolizer_enabled" doc:"hidden"`
is it not possible to enable this flag wit cli? is this on purpose?

2025-05-07 06:53 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +		}
N/A as per https://github.com/grafana/pyroscope/pull/3799#discussion_r2063051024

2025-05-07 09:05 UTC, marcsanmi commented on pkg/validation/limits.go
> +	SymbolizerEnabled bool `yaml:"symbolizer_enabled" json:"symbolizer_enabled" doc:"hidden"`
Should we enable per tenant flag from cli? In symbolizer.go we have defined:
```go

func (cfg *Config) RegisterFlags(f *flag.FlagSet) {
    f.BoolVar(&cfg.Enabled, "symbolizer.enabled", false, "Enable symbolization for unsymbolized profiles")
    ...
}
```

2025-05-07 20:40 UTC, marcsanmi commented on pkg/test/integration/testdata/otel-ebpf-profiler-pyrosymbolized-docker.json.bin
> -            "cat 0x402462[]@:0"
This is because we [removed](https://github.com/grafana/pyroscope/pull/3799/files#diff-30b0385316ef719e3cf6b51bae2226ac4d6afd84b5861f2d3a67abbccbefb762L221) this code from convert that was populating with line when none available:
```go
if len(gl.Line) == 0 {
		gl.Line = append(gl.Line, &googleProfile.Line{
			FunctionId: p.addfunc(fmt.Sprintf("%s 0x%x", p.src.StringTable[om.FilenameStrindex], ol.Address)),
		})
	}
```

2025-05-08 10:32 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	if s.checkObjectStoreCache(ctx, req) {
Let's rewrite `checkObjectStoreCache` and `fetchAndCacheFromDebuginfod` a bit.
Currently they are doing multiple things and I'd like them to do less.

Lets change them to be`fetchLidiaFromObjsotre` and `fetchLidiaFromDebuginfod`.  
The first one just fetches lidia bytes from objstore and does no symbolization. The second one will fetch debug elf and convert it to lidia and return lidia bytes and does not perform symbolization.

very approximate pseudocode
```go
func fetchLidia() []byte, error {


    lidiaBytes, err := s.bucket.Get(req.buildid)
    if err == nil {
        return lidiaBytes, nill
    }
    if !isNotFoundErr(err) {
        return nil, err
    }
    lidiaBytes, err = fetchLidiaFromDebuginfod(req.buildid)
    if err != nil {
        return nil,  err    
    }
    err := s.bucket.Upload(req.buildid, lidiaBytes) 
    if err != nil {
        return nil, err
    }
    return lidiaBytes, err          
}

...
lidiaBytes, err := fetchLidia(req.builid)
table, err := lidia.Open(lidiaBytes)
if err != nil {
    return err
}

s.symbolizeWithTable(table, req)
```

2025-05-08 10:33 UTC, korniltsev commented on pkg/experiment/symbolizer/types.go
> +type Request struct {
I think this is not used outside the package, we can make it not exporter

2025-05-08 10:34 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +func (s *Symbolizer) Symbolize(ctx context.Context, req *Request) error {
I think this is not used outside the package, we can make it unexported

2025-05-08 10:39 UTC, korniltsev commented on pkg/test/integration/testdata/otel-ebpf-profiler-offcpu-cpu.json.bin
> -          "lines": [
I think we still something is broken here and we now do not output the stubs.
I also think is mostly important for profiler developers and me, but not the profiling users. 
I will resolve this, we can address this later

2025-05-08 11:03 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfo_store.go
> +type NullDebugInfoStore struct{}
yes, this was here before having the mocks. Updated.

2025-05-08 11:15 UTC, marcsanmi commented on pkg/experiment/symbolizer/types.go
> +type Request struct {
Yes, I also unexported other types not used outside the packages :)

2025-05-08 21:23 UTC, marcsanmi commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +}
We decided to not filter by otel profiler for now. See https://github.com/grafana/pyroscope-squad/issues/436

2025-05-09 03:23 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		s.metrics.profileSymbolization.WithLabelValues(status).Observe(time.Since(start).Seconds())
this metric is touched twice - once for the whole pprf and once for the permapping request. I suggest we remove the latter one or create a separate metric for it.

2025-05-09 03:29 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +			s.metrics.debuginfodRequestDuration.WithLabelValues(statusErrorNotFound).Observe(time.Since(debuginfodStart).Seconds())
please take another look at this metric. Something is off here. it looks like error statuses are accounted multiple times, in the DebugInfodClient and in the symbolizer. Can we remove all the usages of debuginfod metrics from the symbolizer?

2025-05-09 03:31 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		if errors.As(err, &bnfErr) {
what is the purpose of this type assertion? both branches are the same and return err. Is this needed? can we jsust return err?

2025-05-09 03:36 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		if errors.As(err, &bnfErr) {
I suggest we do not fail the query if there are any errors during symbolization. Let's treat all the errors the same - createNotFoundSymbolz

2025-05-09 03:36 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		s.metrics.debugSymbolResolution.WithLabelValues("lidia_error").Observe(0)
I suggest we do not fail the query if there are any errors during symbolization. Let's treat all the errors the same - createNotFoundSymbolz

2025-05-09 03:36 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +		if err := s.symbolizeLocationsForMapping(ctx, profile, mappingID, locations); err != nil {
I suggest we do not fail the query if there are any errors during symbolization. Let's treat all the errors the same - createNotFoundSymbolz

2025-05-09 03:38 UTC, korniltsev commented on pkg/experiment/symbolizer/types.go
> +	mapping *pprof.Mapping
this field is unused. Let's remove it

2025-05-09 03:40 UTC, korniltsev commented on pkg/experiment/symbolizer/types.go
> +type locToSymbolize struct {
I think we can replace locToSymbolize with just `*googlev1.Location` because `loc.Id == idx +1`

2025-05-09 03:45 UTC, korniltsev commented on pkg/experiment/symbolizer/reader.go
> +			gr.Close()
can we use defer gr.Close() ?

2025-05-09 03:48 UTC, korniltsev commented on pkg/experiment/symbolizer/reader.go
> +	br := bufio.NewReader(r)
lets accept []byte as an argument to this function and do not use bufio - we already have everything in memory, no need to buffer. Let's return []byte here instead of ReaderAt - it will make it a bit more visible that we are reading and decompressing everything fully in memory

2025-05-09 03:50 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	level.Error(s.logger).Log(
nit: this is not an error if it is "not found"

2025-05-09 03:54 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +func (s *Symbolizer) updateProfileWithSymbols(profile *googlev1.Profile, mapping *googlev1.Mapping, locs []locToSymbolize, symLocs []*location) {
Can we reorganize the code a bit, to call this function once per pprof instead of once per mapping? Othervise we create all the maps multiple times

2025-05-09 03:56 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +					StartLine: int64(line.LineNumber),
lets remove this line. On the left we have the start of the function and on the right we have the middle of the function. Also the line number is not included in the key. Also we don't really have line numbers at the moment.

2025-05-09 04:00 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(0)
can we do `maxFuncId := len(profile.Function) + 1` here? I know I told you sometime ago it's not a valid approach in general, but it is a valid approach for pprof files returned from our pprof queries. so should be fine?

2025-05-09 04:01 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +					StartLine: int64(line.LineNumber),
we also don' really have filenames yet. I suggest we remove filename here as well.

2025-05-09 04:07 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	objstoreReader, err := s.store.Get(ctx, buildID)
can we avoid store.Get invocations if we already know debuginfod returned NotFound ? it would probably require to pull the cache from debuginfod into symbolizer

2025-05-09 05:13 UTC, korniltsev commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +	return len(slices.Collect(metadata.FindDatasets(block, matcher))) > 0
@aleks-p Can you help me verify my assumption here please.
1. Blocks contain multiple datasets and so a block may have both unsymbolized and symbolized datasets.
2. I believe the `MetadataQueryService.QueryMetadata` does not return all the datasets present in the block ,but only the ones that matched query.  I've made this conclusion from reading this code
https://github.com/grafana/pyroscope/blob/d564c76454a93f75d008c3a0b223102cdaf55c5c/pkg/experiment/metastore/index/query.go#L163

If my understanding is correct, than this  `hasUnsymbolizedProfiles` is fine. If the second assumption is not correct, then this check would degrade the symbolized query. 

I think everything is good here, just want another :eyes: to doublecheck.

2025-05-17 08:54 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(0)
hmm you're right. I've checked it and seems we do guarantee this so we can remove the loop to find `maxFuncID`, good one 👍

2025-06-03 10:49 UTC, korniltsev commented on pkg/experiment/symbolizer/metrics.go
> +	profileSymbolization *prometheus.HistogramVec
please check the usage of this metric. I think it is used twice - once per mapping, second per all mappings. One of them should go.

2025-06-03 10:52 UTC, korniltsev commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +		if i < len(originalQueries) && originalQueries[i].QueryType == queryv1.QueryType_QUERY_TREE {
lets add an early return (with an error?) for a case if len(originalQueries) != len(resp.Reports)

2025-06-03 10:54 UTC, korniltsev commented on pkg/experiment/symbolizer/debuginfo_store.go
> +type DebugInfoStore interface {
why do we need this interface? can we use `objstore.Bucket` interface directly?

2025-06-03 11:02 UTC, korniltsev commented on pkg/experiment/symbolizer/debuginfo_store.go
> +		if c.bucket.IsObjNotFoundErr(err) {
why do we need special case handling here? why not always wrap? or always just return the err?

2025-06-03 11:04 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +func (s *Symbolizer) symbolizeWithTable(_ context.Context, table *lidia.Table, req *request) {
lets remove context if it is not needed

2025-06-03 11:10 UTC, korniltsev approved these changes
lgtm overall

I left a bunch of nitpick comments.

I am not excited we have to implement `memoryBuffer`. At the same time I don't know any ready to use structure from any library. Maybe in the future we can rework lidia writing api to operate on bytes.Buffer instead of `WriteSeeker`

I think it should not impact the regular read path. I think we should run this in test/dev once again and merge.

I did not test/run this revision locally manually this time.

2025-06-03 15:42 UTC, aleks-p commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +	return len(slices.Collect(metadata.FindDatasets(block, matcher))) > 0
Sorry I missed this @korniltsev . Both assumptions are correct. Depending on the query you can get a mix of mismatching datasets, but since this is in the context of symbolization the datasets should be for the same service.

2025-06-04 05:30 UTC, kolesnikovae commented on cmd/pyroscope/help-all.txt.tmpl
> +    	[experimental] When symbolizer.enabled is true, this controls whether symbolization is enabled for tenants by default. Can be overridden per-tenant. (default true)
If it depends on v2, it should not be shown here unless v2 is enabled

I think it should be just `-symbolizer.enabled` (false by default). Then, the tenant level override controls it at the tenant level (true). LMKWYT

Could you please elaborate on why we need this parameter?

2025-06-04 06:29 UTC, kolesnikovae commented on pkg/frontend/read_path/query_frontend/query_frontend.go
> +	return len(slices.Collect(metadata.FindDatasets(block, matcher))) > 0
I confirm this.

2025-06-04 09:40 UTC, marcsanmi commented on cmd/pyroscope/help-all.txt.tmpl
> +    	[experimental] When symbolizer.enabled is true, this controls whether symbolization is enabled for tenants by default. Can be overridden per-tenant. (default true)
Maybe I understood overrides wrong, but I added that flag to set it to default as true for all tenants. How, otherwise we can set it to true for all tenants by default? Should we hook into the `UnmarshalYAML`?

2025-06-04 10:32 UTC, kolesnikovae commented on cmd/pyroscope/help-all.txt.tmpl
> +    	[experimental] When symbolizer.enabled is true, this controls whether symbolization is enabled for tenants by default. Can be overridden per-tenant. (default true)
Yeah, it's all cool, we only need to make sure:
1. It's not visible in the help message unless v2 is enabled.
2. The parameter name looks good (`-symbolizer.enabled` – without `tenant-` – looks good IMO).
3. We're absolutely sure we do want to enable it by default – I guess makes sense to keep it disabled by default until we mark the feature stable.

2025-06-04 10:35 UTC, kolesnikovae commented on pkg/phlare/phlare.go
> +	}
Let's move it to `registerServerFlagsWithChangedDefaultValues`, where we handle v2 flags:
https://github.com/grafana/pyroscope/blob/main/pkg/phlare/phlare.go#L226-L255

2025-06-04 14:54 UTC, marcsanmi commented on pkg/experiment/symbolizer/debuginfo_store.go
> +		if c.bucket.IsObjNotFoundErr(err) {
N/A as per https://github.com/grafana/pyroscope/pull/3799#discussion_r2123449669

2025-06-05 10:39 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(len(profile.Function) + 1)
@korniltsev I got a panic index out of bounds, so not sure we can rely on function IDs to be sequential (maybe something else is wrong?). For now I'm reverting the change back to:
```go
funcMap := make(map[funcKey]uint64)
maxFuncID := uint64(0)

for _, fn := range profile.Function {
    if fn.Id > maxFuncID {
	maxFuncID = fn.Id
    }
    funcMap[funcKey{fn.Name, fn.Filename}] = fn.Id
}
```

2025-06-05 10:56 UTC, korniltsev commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(len(profile.Function) + 1)
can you reproduce? I suggest we understand / reproduce why it paniced before reverting. And maybe have a testcase.

2025-06-05 11:52 UTC, kolesnikovae commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(len(profile.Function) + 1)
`func.ID - 1` points to the function index in the `Function` slice. If it's not the case, it's a bug, and it should be fixed. Note that 0 ID is a sentinel and it cannot be valid.

2025-06-06 08:09 UTC, marcsanmi commented on pkg/experiment/symbolizer/symbolizer.go
> +	maxFuncID := uint64(len(profile.Function) + 1)
The symbolizer was creating non-sequential function IDs when adding new functions to profiles with existing functions due to 
```go
maxFuncID := uint64(len(profile.Function) + 1)
``` 
However, tree conversion assumes sequential IDs and tries to access [profile.Function[loc.Line[l].FunctionId-1]](https://github.com/grafana/pyroscope/pull/3799/files#diff-acf4ab855649a6af94cf68eb16403eeaa957c082a192dd804699e1dfb13cfb67R471), causing index out of bounds panics. 

Fixed by ensuring new function IDs are always sequential starting from the last existing ID by removing the +1 
```go
maxFuncID := uint64(len(profile.Function))
``` 

I've also added a test explicitly testing this behaviour. You can check it in this commit 1a526a1c3526a82e307712e3fb1ecc366c4321c4.

LMKWYT

2025-06-09 07:18 UTC, korniltsev approved these changes

2025-06-09 10:36 UTC, kolesnikovae approved these changes
LGTM! Thank you so much @marcsanmi! 🎉

2025-06-09 10:36 UTC, kolesnikovae commented on pkg/phlare/modules_experimental.go
>  	)
Basically, it looks like we can pass `f.symbolizer` without the check

2025-06-09 10:36 UTC, kolesnikovae commented on pkg/validation/symbolizer.go
> +}
The description appears invalid

2025-06-10 06:58 UTC, merged